101:
  Title: 【拡散】 Twitterリツイートで拡散させるキャンペーン
  MainAction: 21
  Param:
    type: 1
    basic_type: 101
    shipping: all
    announce: 0
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 21
      3: 4
      4: 9
    2:
      1: 3
102:
  Title: 【拡散】 Twitterでハッシュタグを拡散させるキャンペーン
  MainAction: 18
  Param:
    type: 1
    basic_type: 102
    shipping: all
    announce: 0
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 18
      3: 4
      4: 9
    2:
      1: 3
103:
  Title: 【拡散】 投票結果を拡散させるキャンペーン
  MainAction: 23
  Param:
    type: 1
    basic_type: 103
    shipping: all
    announce: 0
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 23
      3: 4
      4: 9
    2:
      1: 3
104:
  Title: 【リサーチ】 アンケート収集キャンペーン（ユーザー調査 等）
  MainAction: 5
  Param:
    type: 1
    basic_type: 104
    shipping: all
    announce: 0
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 5
      3: 4
      4: 9
    2:
      1: 3
105:
  Title: 【リサーチ】 商品のモニターキャンペーン（事前アンケートアリ）
  MainAction: 5
  Param:
    type: 1
    basic_type: 105
    shipping: all
    announce: 0
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 5
      3: 4
      4: 9
    2:
      1: 3
      2: 5
      3: 1
106:
  Title: 【コンテンツ集め】 写真を投稿してもらうキャンペーン（フォトコンテスト 等）
  MainAction: 2
  Param:
    type: 1
    basic_type: 106
    shipping: all
    announce: 0
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 2
      3: 4
      4: 9
    2:
      1: 3
107:
  Title: 【コンテンツ集め】 Instagramに投稿してもらうキャンペーン
  MainAction: 4
  Param:
    type: 1
    basic_type: 107
    shipping: all
    announce: 0
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 4
      3: 20
      4: 9
    2:
      1: 3
108:
  Title: 【認知UP】 Twitterアカウントのフォロー獲得キャンペーン
  MainAction: 14
  Param:
    type: 1
    basic_type: 108
    shipping: all
    announce: 0
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 14
      3: 4
      4: 9
    2:
      1: 3
109:
  Title: 【認知UP】 動画視聴＋YouTubeチャンネル登録してもらうキャンペーン
  MainAction: 12
  Param:
    type: 1
    basic_type: 109
    shipping: all
    announce: 0
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 12
      3: 22
      4: 4
      5: 9
    2:
      1: 3
110:
  Title: 【認知UP】 毎日参加してもらう、スピードくじキャンペーン
  MainAction: 10
  Param:
    type: 1
    basic_type: 110
    shipping: elected
    announce: 2
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 10
      3: 4
      4: 3
111:
  Title: 【集客】 クーポン配布キャンペーン
  MainAction: 3
  Param:
    type: 1
    basic_type: 111
    shipping: none
    announce: 1
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 3
      3: 11
112:
  Title: 【購入必須】 識別コードで応募してもらうキャンペーン
  MainAction: 19
  Param:
    type: 1
    basic_type: 112
    shipping: all
    announce: 0
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 19
      3: 4
      4: 9
    2:
      1: 3
113:
  Title: 【購入必須】 購入済みレシート写真で応募してもらうキャンペーン
  MainAction: 2
  Param:
    type: 1
    basic_type: 113
    shipping: all
    announce: 0
    join_limit_flg: 0
  Group:
    1:
      1: 0
      2: 2
      3: 4
      4: 9
    2:
      1: 3
